name: Node.js CI

on:
  push:
    branches: ["master"]
env:
  # MONGO_URI: ${{ secrets.MONGO_URI }}
  # JWT_SECRET: ${{ secrets.JWT_SECRET }}
  # JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
  # NODE_ENV: ${{ secrets.NODE_ENV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
    
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
         args: deploy
       